### ISSUE TITLE
[BUG] NoRecipeBook incompatibility

### ISSUE THREAD

**Issue by DanMeadWasTaken** [samolego/ClientStorage#22] opened 2023-01-31 10:53 UTC
this is the log, it simply just seems to be crashing when opening the crafting table and NoRecipeBook or any such related mod is enabled.

https://mclo.gs/hbtgzdd

**Comment by samolego** [comment] 2023-01-31 11:28
Duplicate of #23

**Closed by samolego** 2023-01-31 11:28 UTC

**Comment by DanMeadWasTaken** [comment] 2023-01-31 12:45
could you be more specific on what version of YetAnotherConfigLib i need to use??  according to prism, I'm using the latest version... not to mention, the cause of the two crashes were because of different things- atleast according to those logs

**Comment by DanMeadWasTaken** [comment] 2023-01-31 12:53
also- i don't think this is because of yacl-

![image](https://user-images.githubusercontent.com/75497984/215765321-ef220870-231d-484f-9a8c-4230834b3250.png)

**Comment by samolego** [comment] 2023-01-31 12:59
I'm sorry, I must have been looking at the same error twice, thinking this is a duplicate.

**Comment by samolego** [comment] 2023-01-31 13:02
Seems like there's an index exception within the mod `easiercrafting`
